trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotnetVersion: 'net8.0'
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }} :
    environment : 'staging'
  ${{ else }} :
    environment : 'production'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'nuget restore'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/src'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: DotNetCoreCLI@2
  displayName: 'dotnet build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'
